### ISSUE TITLE
Firmware source code

### ISSUE THREAD

**Issue by gyurco** [neptunoplus/Binaries#1]
[The project description](https://antoniovillena.com/product/neptuno-plus/) says:
- RP2040 based middle board with MiST firmware

The original Minimig firmware was GPL, so the MiST firmware inherited this property. So if your firmware based on MiST's, then please share your derived work.

**Comment by antoniovillena** [comment]
This is also GPL. All sources are published and linked in a visible page. In this case I just added in the readme where there are the firmware binaries:

https://github.com/neptunoplus/Binaries/tree/main/Firmware

If it's not enough just tell me and I will put more links. And of course if you want to collaborate in this project you are welcomed and we will add to the collaborators list

**Comment by ZXMicroJack** [comment]
I took a fork from mist-firmware around 10 month ago, and have been creating a port for rp2040, which is incomplete, but in a reasonable, albeit messy state.  The fork is a submodule to **mist-firmware-rp2040**.  As Antonio says, this is a public repo, feel free to browse at your leisure.  If you want me to do a more integrated rp2040 port into mist-firmware, I'm more than happy to provide it, and to be honest, would make it easier to share.

**Comment by gyurco** [comment]
It's OK in this form, I just didn't find the link to it.
Probably a hw/RP2040 directory can be added with the appropriate implementations from the build/ directory, if you want to work on it, I can gladly help.
